# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutus.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser



class Ui_MainWindow(object):

    def openNewWindow(self):
        from form import Ui_main
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_main()
        self.ui.setupUi(self.window)
        #MainWindow.hide();
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 660)
        MainWindow.setStyleSheet("background-color: rgb(255, 245, 245);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(290, 80, 241, 16))
        self.line.setStyleSheet("color: rgb(255, 0, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 20, 191, 61))
        self.label.setStyleSheet("font: 28pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(210, 110, 391, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(150, 140, 101, 16))
        self.label_18.setObjectName("label_18")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(140, 10, 120, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        #push Button for Joshi Sir
        self.pushButton_13 = QtWidgets.QPushButton(self.frame)
        self.pushButton_13.setGeometry(QtCore.QRect(230, 170, 35, 35))
        self.pushButton_13.setAutoFillBackground(False)
        self.pushButton_13.setStyleSheet("background-image : url(Images/instagram.png);")
        self.pushButton_13.setText("")
        self.pushButton_13.setFlat(True)
        self.pushButton_13.setObjectName("pushButton_13")
        
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(180, 170, 35, 35))
        self.pushButton_14.setAutoFillBackground(False)
        self.pushButton_14.setStyleSheet("background-image : url(Images/linkedin.png);")
        self.pushButton_14.setText("")
        self.pushButton_14.setFlat(True)
        self.pushButton_14.setObjectName("pushButton_14")
        
        self.pushButton_15 = QtWidgets.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(130, 170, 35, 35))
        self.pushButton_15.setAutoFillBackground(False)
        self.pushButton_15.setStyleSheet("background-image : url(Images/github.png);")
        self.pushButton_15.setText("")
        self.pushButton_15.setFlat(True)
        self.pushButton_15.setObjectName("pushButton_15")

        
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(410, 350, 191, 241))
        self.frame_5.setStyleSheet("border-color: rgb(255, 0, 4);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(3)
        self.frame_5.setMidLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(50, 130, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setGeometry(QtCore.QRect(50, 10, 101, 101))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("Images/swaleha-modified.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        
        #Push Button For Swaleha

        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_7.setGeometry(QtCore.QRect(130, 190, 35, 35))
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setStyleSheet("background-image : url(Images/instagram.png);")
        self.pushButton_7.setText("")
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(lambda: webbrowser.open('https://github.com/Swaleha-2s7'))
        
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 190, 35, 35))
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet("background-image : url(Images/linkedin.png);")
        self.pushButton_8.setText("")
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(lambda: webbrowser.open('https://www.linkedin.com/in/swaleha-shaikh-108079209'))

        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 190, 35, 35))
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("background-image : url(Images/github.png);")
        self.pushButton_9.setText("")
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(lambda: webbrowser.open('https://github.com/Swaleha-2s7'))

        
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(10, 350, 191, 241))
        self.frame_6.setStyleSheet("border-color: rgb(255, 0, 0);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(3)
        self.frame_6.setMidLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_25 = QtWidgets.QLabel(self.frame_6)
        self.label_25.setGeometry(QtCore.QRect(50, 10, 101, 101))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("Images/WhatsApp Image 2021-08-27 at 10.28.59 AM-modified.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")

        #Push buttons for Yuvraj
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setGeometry(QtCore.QRect(30, 190, 35, 35))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-image : url(Images/github.png);")
        self.pushButton.setText("")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: webbrowser.open('https://github.com/Yuvraj-021'))
        
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 190, 35, 35))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-image : url(Images/linkedin.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(lambda: webbrowser.open('https://www.linkedin.com/in/yuvraj-deshmukh-05b751205'))
        
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 190, 35, 35))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background-image : url(Images/instagram.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(lambda: webbrowser.open('https://www.instagram.com/l_______yuvraj_____l/'))

        
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(210, 350, 191, 241))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(3)
        self.frame_7.setMidLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(50, 10, 101, 101))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("Images/sudharshan-modified.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")


        # Push Buttons For Sudharshan
        

        self.pushButton_4 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 190, 35, 35))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("background-image : url(Images/instagram.png);")
        self.pushButton_4.setText("")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(lambda: webbrowser.open('https://instagram.com/g_sudarshan11'))
        
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 190, 35, 35))
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet("background-image : url(Images/linkedin.png);")
        self.pushButton_5.setText("")
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(lambda: webbrowser.open('http://linkedin.com/in/g-sudarshan'))
        
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 190, 35, 35))
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet("background-image : url(Images/github.png);")
        self.pushButton_6.setText("")
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(lambda: webbrowser.open('https://github.com/g-sudarshan'))

        
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(610, 350, 191, 241))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(3)
        self.frame_8.setMidLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setGeometry(QtCore.QRect(60, 130, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_22 = QtWidgets.QLabel(self.frame_8)
        self.label_22.setGeometry(QtCore.QRect(50, 10, 101, 101))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("Images/Sejal-modified.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        


        #push Buttons For Sejal

        self.pushButton_10 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_10.setGeometry(QtCore.QRect(130, 190, 35, 35))
        self.pushButton_10.setAutoFillBackground(False)
        self.pushButton_10.setStyleSheet("background-image : url(Images/instagram.png);")
        self.pushButton_10.setText("")
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(lambda: webbrowser.open('http://instagram.com/sejal.1505'))

        self.pushButton_11 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 190, 35, 35))
        self.pushButton_11.setAutoFillBackground(False)
        self.pushButton_11.setStyleSheet("background-image : url(Images/linkedin.png);")
        self.pushButton_11.setText("")
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(lambda: webbrowser.open('http://linkedin.com/in/sejal-jadhav'))

        self.pushButton_12 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 190, 35, 35))
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet("background-image : url(Images/github.png);")
        self.pushButton_12.setText("")
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(lambda: webbrowser.open('https://github.com/sejal-7'))

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 20, 65, 65))
        self.pushButton_4.setStyleSheet("background-image: url(Images/left.png)")
        self.pushButton_4.setText("")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.openNewWindow) 

        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "About us"))
        self.label_18.setText(_translate("MainWindow", "Hrushikesh Joshi"))
        self.label_4.setText(_translate("MainWindow", "Swaleha Shaikh"))
        self.label_2.setText(_translate("MainWindow", "Yuvraj Deshmukh"))
        self.label_3.setText(_translate("MainWindow", "Sudharshan Gawale"))
        self.label_5.setText(_translate("MainWindow", "Sejal Jadhav"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
