# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extract.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
import csv
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidget, QApplication, QMainWindow, QTableWidgetItem, QFileDialog, QHeaderView, QHBoxLayout, QVBoxLayout
import pandas as pd



class Extract_Ui_MainWindow(object):
    # def __init__(self):
    #     super().__init__()
    #     #self.window_width, self.window_height = 700, 500
    #     #self.resize(self.window_width, self.window_height)
    #     #self.setWindowTitle('Load Excel (or CSV) data to QTableWidget')

    #     layout = QVBoxLayout()
    #     self.setLayout(layout)

    #     self.table = QTableWidget()
    #     layout.addWidget(self.table)

        
    #     layout.addWidget(self.button)

    def loadExcelData(self, excel_file_dir, worksheet_name):
        df = pd.read_excel(excel_file_dir, worksheet_name)
        if df.size == 0:
            return
        df.fillna('', inplace=True)
        self.table.setRowCount(df.shape[0])
        self.table.setColumnCount(df.shape[1])
        self.table.setHorizontalHeaderLabels(df.columns)

        for row in df.iterrows():
            values = row[1]
            for col_index, value in enumerate(values):
                if isinstance(value, (float, int)):
                    value = '{0:0,.0f}'.format(value)
                tableItem = QTableWidgetItem(str(value))
                self.table.setItem(row[0], col_index, tableItem)

        self.table.setColumnWidth(2, 300)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #self.button = QPushButton('&Load Data')
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setIconSize(QtCore.QSize(100, 100))
        self.button.setObjectName("button")
        self.button.setGeometry(QtCore.QRect(60, 240, 281, 111))
        self.button.clicked.connect(lambda _, xl_path= 'output.xlsx', sheet_name='output': self.loadExcelData(xl_path, sheet_name))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button.setText(_translate("main", " Data"))

if __name__ == "__main__":
    import sys
    # excel_file_path =
    # worksheet_name = ''
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Extract_Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

