# -*- coding: utf-8 -*-
"""Resume_Extraction_to_Excel .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sGh7h7_-e2h5Oacatneqb-42pgqOgL7n
"""

#!pip install pyresparser

# nltk
#!python -m nltk.downloader words
#!python -m nltk.downloader stopwords

"""Extract Resume Data"""
import csv
from pyresparser import ResumeParser

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, \
    QPushButton, QVBoxLayout, QFileDialog

#import en_core_web_sm
#nlp = en_core_web_sm.load()

# RESUME PARSER PICT v1.0





"""Write Extracted data to CSV file"""







class MainWindow(QMainWindow):
    def __init__(self, parent=None):#--------------
        super(MainWindow, self).__init__(parent)#  |
        self.setWindowTitle("open file dialog")#   |
#                          |
        btn = QPushButton("Open File")#            |---- Just initialization
        layout = QVBoxLayout()#            |
        layout.addWidget(btn)#                     |
        widget = QWidget()#                        |
        widget.setLayout(layout)#                  |
        self.setCentralWidget(widget)#-------------

        btn.clicked.connect(self.open) # connect clicked to self.open()
        self.show()

    

    def extractResume (self, filepath):
        data = ResumeParser(filepath).get_extracted_data()
        return data


    def writeToCSV (self, data):
        data_file = open('output.csv', 'w+', newline='')
        csv_writer = csv.writer(data_file)

        # Writing data into csv file
        header = data.keys()
        csv_writer.writerow(header)
        csv_writer.writerow(data.values())   # Sejal Resume      <-- data
        print("Data inserted successfully...!  :)")
        print(data)
        data_file.close()
    

    def open(self):
        path = QFileDialog.getOpenFileName(self, 'Open a file', '',
                                        'All Files (*.*)')
        if path != ('', ''):
            extracted_Data = self.extractResume("C:/Users/G.Sudarshan/Downloads/Sejal resume.pdf") # Write extracted data to CSV file
            print("Processing....")
            self.writeToCSV(extracted_Data)
            print("File written successfully")
             

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    sys.exit(app.exec_())
    
    
 # ending comment
